[general]
import = [
    "~/.config/alacritty/themes/github-dark.toml"
]

[terminal.shell]
program = "/bin/zsh"

[window]
startup_mode = "Maximized"
dynamic_title = false

[font]
normal = { family = "FiraCode Nerd Font", style = "Regular" }
